"""Generate embeddedCharacters.ts with base64-encoded character PNGs."""
import base64, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHARS_DIR = os.path.join(ROOT, "webview-ui", "public", "assets", "characters")
OUT_PATH = os.path.join(ROOT, "webview-ui", "src", "office", "sprites", "embeddedCharacters.ts")

lines = [
    "// Auto-generated by scripts/gen_embedded_chars.py — DO NOT EDIT.",
    "// Embedded character sprite PNGs as base64 data URIs.",
    "// This bypasses the extension host -> postMessage -> Image load pipeline.",
    "",
]

names = ["char_employeeA", "char_employeeB"]
for name in names:
    path = os.path.join(CHARS_DIR, f"{name}.png")
    with open(path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode("ascii")
    key = name.replace("char_employee", "")
    lines.append(f'export const CHAR_{key}_DATA_URI = "data:image/png;base64,{b64}";')
    lines.append("")

lines.append("export const EMBEDDED_CHARACTERS: Array<{ id: string; uri: string }> = [")
lines.append('  { id: "char_employeeA", uri: CHAR_A_DATA_URI },')
lines.append('  { id: "char_employeeB", uri: CHAR_B_DATA_URI },')
lines.append("];")
lines.append("")

output = "\n".join(lines)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(output)
print(f"Wrote {len(output)} chars to {OUT_PATH}")
